services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    build: ./app/postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./app/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: vectordb

  fastapi:
    build:
      context: .
      dockerfile: app/fastapi/Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

volumes:
  redis_data:
  postgres_data:
