services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    build: ./app/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: vectordb

  fastapi:
    build:
      context: .
      dockerfile: app/fastapi/Dockerfile
    env_file: .env
    environment:
      DB_USER: admin
      DB_PASSWORD: admin
      DB_PORT: 5432
      DB_NAME: vectordb
      ENV: compose
      REDIS_PORT: 6379
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

volumes:
  redis_data:
  postgres_data:
